### ISSUE TITLE
Does this do anything?

### ISSUE THREAD

**Issue by blueyed** [redotjs/redot-lint#6]
According to https://github.com/redotjs/redot-lint/blob/master/packages/redot-lint/redot-lint.js there appears to be no real functionality / linting, is there?

Also it would be nice to have installation instructions to use this via CLI.

**Comment by ChristianMurphy** [comment]
Hey @blueyed,
`redot-lint` is still in progress.
https://github.com/redotjs/dotast-comment-marker and https://github.com/redotjs/redot-message-control/blob/master/redot-message-control.js
need to be wired together, then rules and configurations can be added.

PRs are welcome!
